/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package atencionurgencia.ingreso;

import entidades.SumSuministro;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alvaro Monsalve
 */
public class pDatosMedicCombi extends javax.swing.JPanel {
    private JPopupMenu pop;

    /**
     * Creates new form pDatosMedic
     */
    public pDatosMedicCombi(final JPopupMenu pop) {
        initComponents();
        this.pop=pop; 
    }
    
    public void setShowDat(DefaultTableModel model, String Via,String obs){
        String text="";
        for(int i=0;i<model.getRowCount();i++){
            if((Boolean)model.getValueAt(i, 3)){
                text=text+"SOLUCION PARA DILUIR/MEDICAMENTO PRAL.\n";
                text =text+((SumSuministro)model.getValueAt(i, 0)).toString();
                text=text + "["+model.getValueAt(i, 1).toString()+" - "+model.getValueAt(i, 2).toString()+"]\n"
                        + "- - - - - - - - - - - -\n";
            }else{
                text =text+((SumSuministro)model.getValueAt(i, 0)).toString();
                text=text+" ["+model.getValueAt(i, 1).toString()+" - "+model.getValueAt(i, 2).toString()+"]\n"; 
            }
        }
        jTextArea23.setText(text);
        jLabel16.setText(Via);
        jTextArea22.setText(obs);
        jTextArea23.setCaretPosition(0);
        jTextArea22.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextArea22 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTextArea23 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("Medicamento:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("Via:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel11.setText("Observaciones:");

        jScrollPane21.setMaximumSize(new java.awt.Dimension(164, 20));
        jScrollPane21.setMinimumSize(new java.awt.Dimension(164, 20));
        jScrollPane21.setPreferredSize(new java.awt.Dimension(164, 20));

        jTextArea22.setColumns(20);
        jTextArea22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextArea22.setForeground(new java.awt.Color(0, 102, 255));
        jTextArea22.setLineWrap(true);
        jTextArea22.setRows(2);
        jTextArea22.setText("...");
        jTextArea22.setMaximumSize(new java.awt.Dimension(164, 40));
        jTextArea22.setMinimumSize(new java.awt.Dimension(164, 40));
        jScrollPane21.setViewportView(jTextArea22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete16x16.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 102, 255));
        jLabel16.setText("...");

        jScrollPane22.setMaximumSize(new java.awt.Dimension(164, 20));
        jScrollPane22.setMinimumSize(new java.awt.Dimension(164, 20));
        jScrollPane22.setPreferredSize(new java.awt.Dimension(164, 20));

        jTextArea23.setColumns(20);
        jTextArea23.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextArea23.setForeground(new java.awt.Color(0, 102, 255));
        jTextArea23.setLineWrap(true);
        jTextArea23.setRows(2);
        jTextArea23.setText("...");
        jTextArea23.setMaximumSize(new java.awt.Dimension(164, 40));
        jTextArea23.setMinimumSize(new java.awt.Dimension(164, 40));
        jScrollPane22.setViewportView(jTextArea23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                    .addComponent(jScrollPane22, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane22, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        pop.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JTextArea jTextArea22;
    private javax.swing.JTextArea jTextArea23;
    // End of variables declaration//GEN-END:variables
}
