/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package atencionurgencia.evolucion;

import atencionurgencia.AtencionUrgencia;
import entidades.InfoHistoriac;
import java.awt.Toolkit;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import oldConnection.Database;
import other.FormPersonas;
import tools.Funciones;

/**
 *
 * @author Alvaro Monsalve
 */
public class panelEvolucion extends javax.swing.JPanel {
    FormPersonas personas=null;
    private InfoHistoriac infoHistoriac;
    private JPanel pSignosVitales=null;
    private JPanel pExploracionF=null;

    /**
     * Creates new form panelEvolucion
     */
    public panelEvolucion() {
        initComponents();
        jLabel1.setVisible(false);
    }
    
    private void activeCheck(int val){
        switch(val){
            case 1:
                jCheckBox6.setSelected(true);
                jCheckBox7.setSelected(false);
                break;
            case 2:
                jCheckBox6.setSelected(false);
                jCheckBox7.setSelected(true);
                break;
        }
    }
    
    public void showHC(InfoHistoriac infoHistoriac){
        this.infoHistoriac = infoHistoriac;
        jlbNombrePaciente.setText(infoHistoriac.getIdInfoAdmision().getIdDatosPersonales().getNombre1()+" "
                +infoHistoriac.getIdInfoAdmision().getIdDatosPersonales().getApellido1()+" ["
                +infoHistoriac.getIdInfoAdmision().getIdDatosPersonales().getNumDoc()+"]");
    }
    
    /**
     * Muestra reporte del historial clinico de la admision actual
     */
    public void showHistorialClinic(){
        String master = System.getProperty("user.dir")+"/reportes/HClinica.jasper";
        if(master!=null){
            try {
                oldConnection.Database db = new Database(AtencionUrgencia.props);
                db.Conectar();
                Map param = new HashMap();
                param.put("idHC",infoHistoriac.getId());
                param.put("NameReport","HISTORIA CLINICA DE URGENCIAS");
                param.put("servicio","URGENCIAS");
                param.put("version","1");
                param.put("codigo","HC.U.R1");
                JasperPrint informe = JasperFillManager.fillReport(master, param,db.conexion);
                JasperViewer visor = new JasperViewer(informe,false);
                visor.setIconImage(Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icono.png")));
                visor.setTitle("Reporte");
                visor.setVisible(true);
                db.DesconectarBasedeDatos();
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(this,"Eliminando prueba diagnostica: "+ex.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCentro = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jlbNombrePaciente = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(764, 514));
        setMinimumSize(new java.awt.Dimension(764, 514));
        setPreferredSize(new java.awt.Dimension(764, 514));

        jpCentro.setBackground(new java.awt.Color(204, 204, 255));
        jpCentro.setMaximumSize(new java.awt.Dimension(584, 472));
        jpCentro.setMinimumSize(new java.awt.Dimension(584, 472));

        javax.swing.GroupLayout jpCentroLayout = new javax.swing.GroupLayout(jpCentro);
        jpCentro.setLayout(jpCentroLayout);
        jpCentroLayout.setHorizontalGroup(
            jpCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        jpCentroLayout.setVerticalGroup(
            jpCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 204));
        jLabel22.setText("Signos Vitales");
        jLabel22.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel22MouseExited(evt);
            }
        });
        jLabel22.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel22MouseMoved(evt);
            }
        });

        jCheckBox6.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setEnabled(false);

        jlbNombrePaciente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbNombrePaciente.setForeground(new java.awt.Color(0, 102, 255));
        jlbNombrePaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jlbNombrePaciente.setText("NOMBRE");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_22x22.png"))); // NOI18N
        jButton3.setToolTipText("Mas datos del paciente");
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 204));
        jLabel23.setText("Exploracion Fisica");
        jLabel23.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel23MouseExited(evt);
            }
        });
        jLabel23.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel23MouseMoved(evt);
            }
        });

        jCheckBox7.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox7.setEnabled(false);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 204));
        jLabel24.setText("Historial Clinico Reciente");
        jLabel24.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel24.setDoubleBuffered(true);
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel24MouseExited(evt);
            }
        });
        jLabel24.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel24MouseMoved(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Espera.gif"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 204));
        jLabel25.setText("Exploracion Fisica");
        jLabel25.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel25MouseExited(evt);
            }
        });
        jLabel25.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel25MouseMoved(evt);
            }
        });

        jCheckBox8.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox8.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox7))
                            .addComponent(jSeparator1)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jpCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlbNombrePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbNombrePaciente)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        jpCentro.removeAll();
        if(this.pSignosVitales ==null){
            this.pSignosVitales = new pSignosVitales();
        }
        this.pSignosVitales.setBounds(0, 0, 584, 472);
        jpCentro.add(this.pSignosVitales);
        this.pSignosVitales.setVisible(true);
        jpCentro.validate();
        jpCentro.repaint();
        activeCheck(1);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(personas==null){
            personas = new FormPersonas();
            personas.infopaciente = infoHistoriac.getIdInfoAdmision().getIdDatosPersonales();
            //mostrar datos personas
        }else{
            personas.infopaciente = infoHistoriac.getIdInfoAdmision().getIdDatosPersonales();
        }
        personas.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseExited
        Funciones.setLabelInfo();
    }//GEN-LAST:event_jLabel22MouseExited

    private void jLabel22MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseMoved
        Funciones.setLabelInfo("Signos Vitales");
    }//GEN-LAST:event_jLabel22MouseMoved

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        jpCentro.removeAll();
        if(this.pExploracionF ==null){
            this.pExploracionF = new pExploracionF();
        }
        this.pExploracionF.setBounds(0, 0, 584, 472);
        jpCentro.add(this.pExploracionF);
        this.pExploracionF.setVisible(true);
        jpCentro.validate();
        jpCentro.repaint();
        activeCheck(2);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseExited
        Funciones.setLabelInfo();
    }//GEN-LAST:event_jLabel23MouseExited

    private void jLabel23MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseMoved
        Funciones.setLabelInfo("Exploracion Fisica");
    }//GEN-LAST:event_jLabel23MouseMoved
        
    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        new _historialClinic().showHistorial();
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseExited
        Funciones.setLabelInfo();
    }//GEN-LAST:event_jLabel24MouseExited

    private void jLabel24MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseMoved
        Funciones.setLabelInfo("Historial Clinico Reciente");
    }//GEN-LAST:event_jLabel24MouseMoved

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MouseExited

    private void jLabel25MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MouseMoved

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel jlbNombrePaciente;
    private javax.swing.JPanel jpCentro;
    // End of variables declaration//GEN-END:variables

    public class _historialClinic implements Runnable{
        String master=null;
        public void showHistorial(){
            new Thread(this).start();
        }

        @Override
        public void run() {
            jLabel1.setVisible(true);
            showHistorialClinic();
            jLabel1.setVisible(false);
        }
        
    }

}
